# -*- coding: utf-8 -*-
"""time conflict finder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSYz35OaIzrZGZAvU6I2d5mzUhKZFR_U
"""

#######################################################################
# Program Filename: time conflict finder
# Author: Huu Phat Loc Nguyen
# Date: 2026 - 05 - 6
# Input: term, campus, wishlist of classes, and number of classes for this term
# Output: all possible combinations
#######################################################################

import json
import itertools
import csv
import requests
import time
from datetime import datetime

# ==========================================
# 1. TIME AND OVERLAP MATH
# ==========================================

def time_to_minutes(time_str):
    """Converts a time string like '1350' to total minutes since midnight."""
    time_int = int(time_str)
    hours = time_int // 100
    minutes = time_int % 100
    return (hours * 60) + minutes

def dates_overlap(start1_str, end1_str, start2_str, end2_str):
    """Checks if two YYYY-MM-DD date ranges overlap."""
    # If a class is missing dates for some reason, assume they overlap to be safe
    if not all([start1_str, end1_str, start2_str, end2_str]):
        return True

    date_format = "%Y-%m-%d"
    try:
        s1 = datetime.strptime(start1_str, date_format)
        e1 = datetime.strptime(end1_str, date_format)
        s2 = datetime.strptime(start2_str, date_format)
        e2 = datetime.strptime(end2_str, date_format)

        # Standard overlap formula for dates
        return (s1 <= e2) and (s2 <= e1)
    except ValueError:
        # If the API returns weirdly formatted text instead of dates, play it safe
        return True


def check_overlap(class1, class2):
    """Returns True if the two classes have a time and date conflict."""

    # NEW: Check if the calendar dates actually overlap!
    if not dates_overlap(class1.get("start_date", ""), class1.get("end_date", ""),
                         class2.get("start_date", ""), class2.get("end_date", "")):
        return False # They happen in totally different weeks/months!

    # Handle cases where a class might not have meeting times listed
    if not class1.get("meetingTimes") or not class2.get("meetingTimes"):
        return False

    try:
        times1 = json.loads(class1["meetingTimes"])
        times2 = json.loads(class2["meetingTimes"])
    except json.JSONDecodeError:
        return False

    for t1 in times1:
        for t2 in times2:
            if t1["meet_day"] == t2["meet_day"]:
                start1 = time_to_minutes(t1["start_time"])
                end1 = time_to_minutes(t1["end_time"])
                start2 = time_to_minutes(t2["start_time"])
                end2 = time_to_minutes(t2["end_time"])

                # Standard overlap formula for daily times
                if (start1 < end2) and (start2 < end1):
                    return True # Conflict found!

    return False



def schedule_has_conflicts(schedule_tuple):
    """Checks an entire generated schedule for any internal overlaps."""
    # Flatten the schedule (since bundles contain multiple classes)
    flat_schedule = [course for bundle in schedule_tuple for course in bundle]

    # Check every unique pair of classes in the schedule
    for class1, class2 in itertools.combinations(flat_schedule, 2):
        if check_overlap(class1, class2):
            return True
    return False

# ==========================================
# 2. DATA FILTERING & BUNDLING
# ==========================================

def get_available_classes(all_api_classes, desired_course_codes):
    """Filters for open, requested classes and groups them by course code."""
    grouped_classes = {code: [] for code in desired_course_codes}

    for c in all_api_classes:
        code = c.get("code", "").upper()
        # Only keep it if the user wants it, it's not full ('F'), and not cancelled ('Y')
        if code in desired_course_codes and c.get("stat") != "F" and c.get("isCancelled") != "Y":
            grouped_classes[code].append(c)

    return grouped_classes

def bundle_components(course_classes):
    """
    Dynamically pairs up linked components based on section numbers.
    Includes a fallback for parallel standalone tracks (like Ecampus vs Corvallis).
    """
    component_types = list(set([c.get("schd") for c in course_classes]))

    if len(component_types) <= 1:
        return [[c] for c in course_classes]

    primary = [c for c in course_classes if c.get("schd") == component_types[0]]
    secondary = [c for c in course_classes if c.get("schd") == component_types[1]]

    # --- NEW: The Parallel Track Check ---
    # Check which campuses the primary and secondary components exist on
    campuses_primary = set([c.get("camp") for c in primary])
    campuses_secondary = set([c.get("camp") for c in secondary])

    # If they share NO campuses, they are parallel tracks, not pairs.
    # e.g., Corvallis 'A' vs Ecampus 'L'
    if not campuses_primary.intersection(campuses_secondary):
        return [[c] for c in course_classes] # Treat them ALL as standalone!
    # -------------------------------------

    bundles = []

    # Attempt 1: Strict Linkage (Matching first 2 characters)
    for prim in primary:
        for sec in secondary:
            if prim.get("camp") != sec.get("camp"):
                continue

            p_sec = prim.get("no", "")
            s_sec = sec.get("no", "")

            if p_sec and s_sec and (p_sec[:2] == s_sec[:2]):
                if not check_overlap(prim, sec):
                    bundles.append([prim, sec])

    # Attempt 2: Open Linkage (Fallback for Math Department)
    if not bundles:
        for prim in primary:
            for sec in secondary:
                if prim.get("camp") != sec.get("camp"):
                    continue

                if not check_overlap(prim, sec):
                    bundles.append([prim, sec])

    return bundles

# ==========================================
# 3. ANALYSIS AND EXPORT
# ==========================================

def analyze_valid_schedule(valid_combination):
    total_credits = 0.0
    """Calculates total fees, extracts CRNs, and formats the schedule."""
    flat_schedule = [course for bundle in valid_combination for course in bundle]

    total_fees = 0.0
    instructors = set()
    crns = []  # NEW: List to hold the CRNs

    for course in flat_schedule:
        instructors.add(course.get("instr", "TBA"))

        # NEW: Grab the CRN, default to 'N/A' if missing for some reason
        crns.append(course.get("crn", "N/A"))

        fee_str = course.get("ssrFees", "").strip()
        if fee_str:
            try:
                total_fees += float(fee_str)
            except ValueError:
                pass # Ignore if fee string is unreadable
        credit_str = course.get("hours_html", "0").strip()
        try:
          total_credits += float(credit_str)
        except ValueError:
          pass
    return {
    "schedule": flat_schedule,
    "instructors": list(instructors),
    "total_fees": total_fees,
    "total_credits": total_credits,
    "crns": crns
      }

def export_schedules_to_csv(analyzed_schedules, filename="my_possible_schedules.csv"):
    """Writes the successful schedules to a CSV file."""
    if not analyzed_schedules:
        print("\nNo valid schedules found. Try adjusting your course list.")
        return

    # NEW: Added "Total Credits" as a new column header before Fees
    headers = ["Option", "Courses", "CRNs", "Meeting Times", "Instructors", "Total Credits", "Total Fees ($)"]

    # Tip: 'utf-8-sig' makes sure Excel reads the '$' symbols correctly
    with open(filename, mode='w', newline='', encoding='utf-8-sig') as file:
        writer = csv.writer(file)
        writer.writerow(headers)

        for index, sched in enumerate(analyzed_schedules):
            course_codes = ", ".join([c["code"] for c in sched["schedule"]])
            crns = ", ".join(sched["crns"])
            meeting_times = ", ".join([f"{c['code']} ({c.get('meets', 'TBA')})" for c in sched["schedule"]])
            instructors = ", ".join(sched["instructors"])

            # Format the numbers nicely
            fees = f"{sched.get('total_fees', 0):.2f}"

            # NEW: Extract the credits from the dictionary and format to 1 decimal (e.g., "12.0")
            credits = f"{sched.get('total_credits', 0):.1f}"

            # NEW: Make sure 'credits' is added to this list in the exact same order as the headers!
            writer.writerow([index + 1, course_codes, crns, meeting_times, instructors, credits, fees])

    print(f"\nSuccess! Saved {len(analyzed_schedules)} schedule options to {filename}")

# ==========================================
# 4. USER INTERFACE & MAIN PIPELINE
# ==========================================

def get_user_courses():
    """CLI loop for user input with smart co-req reminders."""
    print("--- OSU Schedule Generator ---")
    print("Enter your desired course codes (e.g., 'ENGR 103').")
    print("Type '/' when you are finished.\n")

    # NEW: A dictionary mapping common lectures to their separate labs
    common_coreqs = {
        "CH 231": "CH 261 (Gen Chem Lab)",
        "CH 232": "CH 262 (Gen Chem Lab)",
        "CH 233": "CH 263 (Gen Chem Lab)",
        "PH 211": "PH 221 (Physics Lab)",
        "PH 212": "PH 222 (Physics Lab)",
        "PH 213": "PH 223 (Physics Lab)"
        # You can add more here as you discover them!
    }

    desired_courses = []

    while True:
        user_input = input("Course Code: ").strip().upper()

        if user_input == "/":
            break
        elif user_input == "":
            print("Please enter a valid course code.")
        else:
            desired_courses.append(user_input)

            # NEW: The Smart Reminder
            if user_input in common_coreqs:
                lab_name = common_coreqs[user_input]
                print(f"  💡 Heads up! {user_input} usually requires {lab_name}.")
                print(f"     Make sure to add it to your list if you need it!")

    return desired_courses


def fetch_course_data(course_code, term_code):
    """
    Fetches data using the standard CourseLeaf POST payload structure.
    """
    # 1. Clean the URL (Remove the alias and stat from the link)
    url = "https://classes.oregonstate.edu/api/?page=fose&route=search"

    # Pad with spaces so it completely overwrites previous lines in the terminal
    print(f"Fetching {course_code} for term {term_code}...       ", end="\r")

    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36"
    }

    # 2. Bundle EVERYTHING into the payload (Term + Course Code)
    payload = {
        "other": {
            "srcdb": term_code
        },
        "criteria": [
            {
                "field": "alias",
                "value": course_code  # e.g., "ENGR 103"
            }
        ]
    }

    try:
        # Send the payload via POST
        response = requests.post(url, json=payload, headers=headers)
        response.raise_for_status()
        data = response.json()

        if isinstance(data, dict):
            if "results" in data and isinstance(data["results"], list):
                return data["results"]
            else:
                print(f"\n  -> API returned unexpected data for {course_code}: {data}")
                return []

        elif isinstance(data, list):
            return data
        else:
            return []

    except requests.exceptions.RequestException as e:
        print(f"\n  -> Error connecting to API for {course_code}: {e}")
        return []
    except ValueError:
        print(f"\n  -> Error: API did not return valid JSON for {course_code}.")
        return []
############# GET USER TERM CODE ##############
def get_user_term():
    """
    Dynamically generates the OSU term code based on the season and calendar year.
    Formula:
    - Summer/Fall: (Year + 1) + Suffix (00 or 01)
    - Winter/Spring: Year + Suffix (02 or 03)
    """
    print("\n--- Select Term ---")

    # Mapping the seasons to their API suffixes
    term_suffixes = {
        "1": ("SUMMER", "00"),
        "2": ("FALL", "01"),
        "3": ("WINTER", "02"),
        "4": ("SPRING", "03")
    }

    # 1. Get the Season
    print("1 - Summer\n2 - Fall\n3 - Winter\n4 - Spring")
    while True:
        season_choice = input("Select Season (1-4) [Default: 2 (Fall)]: ").strip()
        if season_choice == "":
            season_choice = "2"

        if season_choice in term_suffixes:
            season_name, suffix = term_suffixes[season_choice]
            break
        print("Invalid choice. Please enter 1, 2, 3, or 4.")

    # 2. Get the Year
    from datetime import datetime
    current_year = datetime.now().year

    while True:
        year_input = input(f"Enter Year (e.g., 2026) [Default: {current_year}]: ").strip()
        if year_input == "":
            calendar_year = current_year
            break

        if len(year_input) == 4 and year_input.isdigit():
            calendar_year = int(year_input)
            break
        print("Invalid year. Please enter a 4-digit year.")

    # 3. Apply the "Academic Year" Math
    if season_name in ["SUMMER", "FALL"]:
        # Summer and Fall belong to the *next* academic year
        academic_year = calendar_year + 1
    else:
        # Winter and Spring belong to the *current* academic year
        academic_year = calendar_year

    # 4. Construct the final 6-digit API code
    api_term_code = f"{academic_year}{suffix}"

    print(f" -> Setting search for {season_name.capitalize()} {calendar_year} (API Code: {api_term_code})")

    return api_term_code
#####################################
def fetch_section_details(unique_key, term_code):
    """Hits the 'details' route to grab the missing credit hours."""
    url = "https://classes.oregonstate.edu/api/?page=fose&route=details"

    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    }

    # CourseLeaf requires the word 'key:' in front of the actual key number
    payload = {
        "key": f"key:{unique_key}",
        "srcdb": term_code
    }

    try:
        response = requests.post(url, json=payload, headers=headers)
        if response.status_code == 200:
            return response.json()
    except:
        pass
    return {}

########### User's campus ###########
def get_user_campus():
    """CLI menu to select the desired campus."""
    print("\nSelect your Campus:")
    print("C   - Corvallis (Main Campus)")
    print("DSC - Ecampus (Distance/Online)")
    print("B   - OSU Cascades")
    print("ALL - Any Campus")

    while True:
        # Defaults to 'C' if the user just presses Enter
        choice = input("Enter campus code (C, DSC, B, ALL) [Default: C]: ").strip().upper()

        if choice == "":
            return "C"
        elif choice in ["C", "DSC", "B", "ALL"]:
            return choice
        else:
            print("Invalid choice. Please enter C, DSC, B, or ALL.")

def main():
    print("--- OSU Schedule Generator ---")
    my_term = get_user_term()


    my_campus = get_user_campus()
    print("\n")

    # 1. Get user input
    my_courses = get_user_courses()
    if not my_courses:
        print("No courses selected. Exiting.")
        return

    print("\n")

    try:
        target_count = int(input("How many classes do you want to take this term? (e.g., 4): "))
    except ValueError:
        print("Invalid number. Defaulting to 4.")
        target_count = 4

    print("\n")

    grouped_classes = {}

    for code in my_courses:
        raw_course_data = fetch_course_data(code, my_term)

        # NEW: Filter by status ('F'), cancellation ('Y'), AND campus code
        available_sections = []
        credit_cache = {} # NEW: Stores credits so we don't spam the API

        for c in raw_course_data:
            is_open = c.get("stat") != "F" and c.get("isCancelled") != "Y"
            is_distance_learning = c.get("camp", "").upper() in ["DI", "DSC", "DL"]
            matches_campus = (my_campus == "ALL") or (c.get("camp", "").upper() == my_campus) or is_distance_learning

            if is_open and matches_campus:
                # --- NEW CREDIT FETCHING LOGIC ---
                # Create a cache label like "ENGR 103-A" or "ENGR 103-R"
                comp_type = c.get("schd", "L")
                cache_label = f"{code}-{comp_type}"

                # If we haven't checked this component type yet, hit the API once
                if cache_label not in credit_cache:
                    details = fetch_section_details(c.get("key"), my_term)

                    # Extract credits (default to 0 if not found)
                    raw_credits = details.get("hours_html", "0")
                    credit_cache[cache_label] = raw_credits

                # Manually inject the credits into the lightweight search data
                c["hours_html"] = credit_cache[cache_label]
                # ----------------------------------

                available_sections.append(c)

        if not available_sections:
            print(f"\nWarning: No open sections found for {code} at campus {my_campus}.")
        else:
            grouped_classes[code] = available_sections

        time.sleep(1)

    print("\nGenerating schedules...")

    # ... (The rest of your bundling and combinations code stays exactly the same!)

   # 4. Create non-overlapping bundles mapped to their course codes
    all_course_bundles = {}
    for code, classes_for_this_course in grouped_classes.items():
        valid_bundles = bundle_components(classes_for_this_course)

        if valid_bundles:
            all_course_bundles[code] = valid_bundles
        else:
            # NEW: Warn the user instead of silently dropping it!
            print(f" -> ⚠️ Dropped {code}: Could not find any valid Lecture + Recitation pairs.")

    # Safety check: Make sure they have enough valid courses to meet their target
    available_course_codes = list(all_course_bundles.keys())
    if len(available_course_codes) < target_count:
        print(f"\nWarning: You only have {len(available_course_codes)} available courses, but requested {target_count}.")
        target_count = len(available_course_codes)

    print(f"\nGenerating all possible {target_count}-class schedules from your wishlist...")

    valid_schedules = []

    # NEW: Step 5a - Pick a subset of courses from the wishlist (e.g., 4 out of 10)
    for selected_courses in itertools.combinations(available_course_codes, target_count):

        # Grab the bundles ONLY for the 4 courses we just selected
        bundles_to_combine = [all_course_bundles[code] for code in selected_courses]

        # Step 5b - Run your normal overlap checker on this specific subset
        for combo in itertools.product(*bundles_to_combine):
            if not schedule_has_conflicts(combo):
                analyzed = analyze_valid_schedule(combo)
                valid_schedules.append(analyzed)

    export_schedules_to_csv(valid_schedules)

if __name__ == "__main__":
    main()

# NOTE
#202700: Summer 2026

#202701: Fall 2026

#202702: Winter 2027

#202703: Spring 2027



#NOTE
#The algorithm prioritizes in-person classes by default.
#If a user wants to adjust their schedule, they can simply swap in the online version of a class, which is guaranteed to fit since online courses do not have time conflicts.